; ─── Base commune ────────────────────────────────────────────
[env]
platform = espressif32@6.5.0
board = m5stack-cores3
framework = arduino
monitor_speed = 115200

build_flags =
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=1

; ─── Firmware datalogger RS-232 + provisioning QR ─────────────
[env:m5stack-cores3]
build_src_filter = +<main_datalogger.cpp>

lib_deps =
    m5stack/M5Unified @ ^0.2.0
    https://github.com/m5stack/M5Module-QRCode
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.0

; ─── Firmware datalogger BLE (provisioning Bluetooth, sans accessoire) ────
[env:datalogger-ble]
build_src_filter = +<main_datalogger_ble.cpp>

lib_deps =
    m5stack/M5Unified @ ^0.2.0
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.0
    h2zero/NimBLE-Arduino @ ^1.4.1
